version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-deps:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/*/src/test/resources/*.dockerfile"
    schedule:
      interval: "weekly"
    groups:
      dockerfiles:
        patterns:
          - "*"
