[versions]
asm = "9.9"
hamcrest = "3.0"
jackson = "3.0.3"
jetbrains-annotations = "26.0.2-1"
jmh = "1.37"
junit = "6.0.1"
logback = "1.5.21"
lombok = "1.18.42"
pcollections = "5.0.0"
slf4j = "2.0.17"
spring-boot = "4.0.0"
testcontainers = "2.0.2"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
hikari = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
jackson-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref="jetbrains-annotations" }
jmh-apt = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jooq = { module = "org.jooq:jooq", version = "3.20.10" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mongodb = { module = "org.mongodb:mongodb-driver-sync", version="5.6.1" }
mysql = { module = "com.mysql:mysql-connector-j", version = "9.5.0" }
opentelemetry = { module="io.opentelemetry:opentelemetry-sdk", version="1.57.0" }
pcollections = { module = "org.pcollections:pcollections", version.ref="pcollections" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.8" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
spring-boot-annotation-processor = { module="org.springframework.boot:spring-boot-configuration-processor", version.ref="spring-boot" }
spring-boot-starter-web = { module="org.springframework.boot:spring-boot-starter-web", version.ref="spring-boot" }
spring-boot-starter-webmvc = { module="org.springframework.boot:spring-boot-starter-webmvc", version.ref="spring-boot" }
spring-boot-starter-test = { module="org.springframework.boot:spring-boot-starter-test", version.ref="spring-boot" }
spring-boot-starter-webmvc-test = { module="org.springframework.boot:spring-boot-starter-webmvc-test", version.ref="spring-boot" }
sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.51.1.0" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-mongodb = { module = "org.testcontainers:testcontainers-mongodb", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:testcontainers-mysql", version.ref="testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref="testcontainers" }
testcontainers-toxiproxy = { module = "org.testcontainers:testcontainers-toxiproxy", version.ref = "testcontainers" }

[plugins]
nexus = { id = "io.github.gradle-nexus.publish-plugin", version="2.0.0" }
spotbugs = { id = "com.github.spotbugs", version = "6.4.7" }
